name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    name: Build with ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.10.2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm install

  test:
    strategy:
      matrix:
        node-version: [18.x]

    name: Run all tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8.10.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm" # Set cache to pnpm
      - name: Install pnpm
      - run: pnpm install # Use pnpm instead of npm

      - if: github.event_name == 'pull_request'
        name: Validate all commits from PR
        run: pnpx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Linter
        run: pnpm run lint # Use pnpm instead of npm

      - name: Type checking
        run: pnpm run check-types # Use pnpm instead of npm

      - name: Run unit tests
        run: pnpm run test # Use pnpm instead of npm

      - name: Install Playwright (used for Storybook and E2E tests)
        run: pnpx playwright install --with-deps

      - name: Run storybook tests
        run: pnpm run test-storybook:ci # Use pnpm instead of npm

      - name: Run E2E tests
        run: pnpx percy exec -- pnpm run test:e2e # Use pnpm instead of npm
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 7
